name: zen_mart_pro
description: A complete Multi-Vendor E-Commerce Ecosystem.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Services
  firebase_core: ^3.10.1
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0       # Added for Vendor Product & Banner Uploads
  firebase_messaging: ^15.0.0

  # Navigation & Routing
  go_router: ^14.0.0

  # State Management
  provider: ^6.1.2

  # UI & Utilities
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1    # Added for optimized image loading
  shared_preferences: ^2.2.3      # Added for secure session caching

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Register assets for Zenvyro Labs branding requirement
  assets:
    - assets/images/